remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: osu.Music
description: Simple music player for your osu! library.
show_downloads: false
