title: osu.Music
description: Simple music player for your osu! library.
show_downloads: true
github.exe_url: https://github.com/Laritello/osu-music/releases/download/0.2.6/Setup.exe

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
